name: flutter_custom_timer
description: A simple customizable countdown timer widget for Flutter.
version: 0.0.1
homepage: https://github.com/yourusername/flutter_custom_timer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# If you add images/fonts/assets later, define them here.
